[package]
name = "lentg/hugo-starter-001"
version = "0.2.1"
description = "Wasmer Hugo starter package"
readme = "README.md"
repository = "https://github.com/lentg/hugo-starter-001"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "public"
